# Generated by Django 5.0.4 on 2026-05-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0025_remove_sitesettings_about_badge_rn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="info_message_active",
            field=models.BooleanField(
                default=False, help_text="Activer/Désactiver le bandeau d'information"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="info_message_link",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Lien optionnel pour le message d'info",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="info_message_text_en",
            field=models.TextField(
                blank=True, default="", help_text="Texte du message d'information (EN)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="info_message_text_fr",
            field=models.TextField(
                blank=True, default="", help_text="Texte du message d'information (FR)"
            ),
        ),
    ]
