# Generated by Django 5.0.4 on 2026-05-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0026_sitesettings_info_message_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="bishop_message_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bishop_message_fr",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bishop_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bishop_photo",
            field=models.ImageField(blank=True, null=True, upload_to="settings/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bishop_title_en",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bishop_title_fr",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="history_image",
            field=models.ImageField(blank=True, null=True, upload_to="settings/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="history_text_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="history_text_fr",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="history_title_en",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="history_title_fr",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mission_badge_en",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mission_badge_fr",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mission_description_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mission_description_fr",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mission_image",
            field=models.ImageField(blank=True, null=True, upload_to="settings/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mission_title_en",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mission_title_fr",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_bishop_en",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_bishop_fr",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_history_en",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_history_fr",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_team_en",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_team_fr",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_vision_en",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_vision_fr",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="organization_subtitle_en",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="organization_subtitle_fr",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="organization_text_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="organization_text_fr",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="organization_title_en",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="organization_title_fr",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="team_badge_en",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="team_badge_fr",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="values_badge_en",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="values_badge_fr",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="values_description_en",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="values_description_fr",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="values_image",
            field=models.ImageField(blank=True, null=True, upload_to="settings/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="values_title_en",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="values_title_fr",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_badge_en",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_badge_fr",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_image",
            field=models.ImageField(blank=True, null=True, upload_to="settings/"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="accent_color",
            field=models.CharField(
                default="#F59E0B", help_text="Couleur d'accentuation", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_btn1_link_en",
            field=models.CharField(blank=True, default="/a-propos", max_length=255),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_btn1_link_fr",
            field=models.CharField(blank=True, default="/a-propos", max_length=255),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_title_en",
            field=models.CharField(
                default="About Us", max_length=255, verbose_name="Titre Hero (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_title_fr",
            field=models.CharField(
                default="À propos de nous",
                max_length=255,
                verbose_name="Titre Hero (FR)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="page_about_title_en",
            field=models.CharField(
                default="About Us",
                max_length=255,
                verbose_name="Titre Page À Propos (EN)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="page_about_title_fr",
            field=models.CharField(
                default="À propos de nous",
                max_length=255,
                verbose_name="Titre Page À Propos (FR)",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="primary_color",
            field=models.CharField(
                default="#1D8B5D",
                help_text="Couleur principale (hex: #RRGGBB)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="secondary_color",
            field=models.CharField(
                default="#19324D", help_text="Couleur secondaire", max_length=20
            ),
        ),
    ]
