# Generated by Django 5.0.4 on 2026-05-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0027_sitesettings_bishop_message_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="nav_about_en",
            field=models.CharField(blank=True, default="About Us", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_about_fr",
            field=models.CharField(blank=True, default="À Propos", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_contact_en",
            field=models.CharField(blank=True, default="Contact", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_contact_fr",
            field=models.CharField(blank=True, default="Contact", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_home_en",
            field=models.CharField(blank=True, default="Home", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_home_fr",
            field=models.CharField(blank=True, default="Accueil", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_news_en",
            field=models.CharField(blank=True, default="News", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_news_fr",
            field=models.CharField(blank=True, default="Actualités", max_length=100),
        ),
    ]
