# Generated by Django 5.0.4 on 2026-05-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "settings",
            "0028_sitesettings_nav_about_en_sitesettings_nav_about_fr_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="info_badge_text_en",
            field=models.CharField(
                blank=True,
                default="INFO SHALOM",
                help_text="Texte du badge (EN)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="info_badge_text_fr",
            field=models.CharField(
                blank=True,
                default="INFO SHALOM",
                help_text="Texte du badge (FR)",
                max_length=50,
            ),
        ),
    ]
