# Generated by Django 5.0.4 on 2026-04-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0017_alter_diocesepresentation_hero_subtitle_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParoissesPresentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="paroisses/",
                        verbose_name="Image Hero (Bandeau)",
                    ),
                ),
                (
                    "hero_badge_fr",
                    models.CharField(
                        blank=True,
                        default="PRÉSENCE COMMUNAUTAIRE",
                        max_length=255,
                        null=True,
                        verbose_name="Badge Hero (FR)",
                    ),
                ),
                (
                    "hero_title_fr",
                    models.CharField(
                        blank=True,
                        default="Nos Paroisses",
                        max_length=255,
                        null=True,
                        verbose_name="Titre Hero (FR)",
                    ),
                ),
                (
                    "hero_subtitle_fr",
                    models.TextField(
                        blank=True,
                        default="Découvrez les paroisses du diocèse de Makamba. De véritables foyers spirituels, au cœur de chaque communauté, pour partager la foi et grandir ensemble.",
                        null=True,
                        verbose_name="Sous-titre Héro (FR)",
                    ),
                ),
                (
                    "hero_badge_en",
                    models.CharField(
                        blank=True,
                        default="COMMUNITY PRESENCE",
                        max_length=255,
                        null=True,
                        verbose_name="Badge Hero (EN)",
                    ),
                ),
                (
                    "hero_title_en",
                    models.CharField(
                        blank=True,
                        default="Our Parishes",
                        max_length=255,
                        null=True,
                        verbose_name="Titre Hero (EN)",
                    ),
                ),
                (
                    "hero_subtitle_en",
                    models.TextField(
                        blank=True,
                        default="Discover the parishes of the Diocese of Makamba. True spiritual homes at the heart of every community.",
                        null=True,
                        verbose_name="Sous-titre Héro (EN)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Présentation de la page Paroisses",
                "verbose_name_plural": "Présentation de la page Paroisses",
            },
        ),
    ]
