# Generated by Django 5.0.4 on 2026-05-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0018_paroissespresentation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom complet")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("subject", models.CharField(max_length=255, verbose_name="Sujet")),
                ("message", models.TextField(verbose_name="Message")),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'envoi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Message de Contact",
                "verbose_name_plural": "Messages de Contact",
                "ordering": ["-created_at"],
            },
        ),
    ]
