# Generated by Django 5.0.4 on 2026-05-08 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0007_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={"ordering": ["-priority", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Commentaire",
                "verbose_name_plural": "Commentaires",
            },
        ),
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.PositiveIntegerField(default=0, verbose_name="J'aime"),
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="announcements.comment",
                verbose_name="Réponse à",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="category",
            field=models.CharField(
                choices=[
                    ("evenement", "Événement"),
                    ("nouvelle", "Nouvelle"),
                    ("communique", "Communiqué"),
                    ("urgent", "Urgent"),
                ],
                default="nouvelle",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="content_en",
            field=models.TextField(blank=True, null=True, verbose_name="Contenu (EN)"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="content_fr",
            field=models.TextField(blank=True, null=True, verbose_name="Contenu (FR)"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="announcements/"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="language",
            field=models.CharField(
                choices=[("fr", "Français"), ("en", "Anglais")],
                default="fr",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Titre (EN)"
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title_fr",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Titre (FR)"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author_name",
            field=models.CharField(
                blank=True,
                default="Anonyme",
                max_length=100,
                verbose_name="Nom de l'auteur",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="Approuvé"),
        ),
    ]
